services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: MVC
    volumes:
      - ./php:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=passSharedPost
      - MYSQL_DATABASE=db_shared_post
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passSharedPost
      MYSQL_DATABASE: db_shared_post
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: passSharedPost
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data: